name: MoneyExample Autograding
setup:
  # Install Java Development Kit (JDK) 17
  - uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: '17'
  # Download JUnit 5 Console Launcher for running tests
  - name: Download JUnit Console Launcher
    run: |
      mkdir -p lib
      curl -L https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.0/junit-platform-console-standalone-1.10.0.jar -o lib/junit-platform-console-standalone.jar
      echo "JUnit Console Launcher downloaded successfully."
run:
  # Compile all Java source files within the 'moneyexample' directory.
  # The -cp (classpath) includes the current directory (.) and the JUnit JAR.
  # Important: The classpath includes the 'moneyexample' directory itself.
  - name: Compile Java Code
    run: |
      # Compile all .java files in the moneyexample/ directory
      # The classpath includes both the JUnit JAR and the directory containing your source files.
      javac -cp "lib/junit-platform-console-standalone.jar:." moneyexample/*.java
      if [ $? -ne 0 ]; then
        echo "Compilation failed. Check your Java syntax in moneyexample/*.java."
        exit 1
      fi
      echo "Java code compiled successfully."

  # Run JUnit tests using the console launcher.
  # --class-path moneyexample/ ensures that compiled classes inside moneyexample/ are found.
  # --scan-classpath discovers test classes automatically.
  # --include-classname "MoneyTest" specifically targets your MoneyTest class.
  - name: Run JUnit Tests
    run: |
      java -jar lib/junit-platform-console-standalone.jar \
        --class-path moneyexample/ \
        --scan-classpath \
        --include-classname "MoneyTest"
      if [ $? -ne 0 ]; then
        echo "Tests failed. Review your moneyexample/MoneyTest.java."
        exit 1
      fi
      echo "All tests passed successfully!"
shell: bash
timeout: 300 # 5 minutes timeout